#!/bin/bash

mysqld --bootstrap <<-EOF
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS \`${WP_DATABASE_NAME}\`;
    CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_USER_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${WP_DATABASE_NAME}\`.* TO '${DB_USER}'@'%' IDENTIFIED BY '${DB_USER_PASSWORD}';
    FLUSH PRIVILEGES;
EOF

exec mysqld
